### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by pi0** [unjs/unimport#1]
## Base
- [x] unimport context
- [x] Add an import to code
- [x] Detect unimported usage of known function/variable
- [ ] Including merging with an existing import declaration
- [ ] Get all exports form a local package (reference: https://github.com/antfu/export-size/blob/main/src/exports.ts#L87)
- [ ] Import resolves (reference: https://github.com/antfu/unplugin-auto-import/pull/23)
- [ ] Add repo description and goal of the project

## Integration

- [x] Unplugin (`unimport/unplugin`)

## Presets
- [x] Define preset
- [x] Resolve preset
- [x] Merge presets and resolve conflicts
- [x] Built-in presets (reference: https://github.com/antfu/unplugin-auto-import/tree/main/src/presets)
